//
// Created by Peter Chen on 5/29/16.
//

#ifndef CUBEWORLD_IMULTIPLAYERCLIENTLISTENER_H
#define CUBEWORLD_IMULTIPLAYERCLIENTLISTENER_H


class IMultiplayerClientListener {

};


#endif //CUBEWORLD_IMULTIPLAYERCLIENTLISTENER_H
