//
// Created by Peter Chen on 5/29/16.
//

#ifndef CUBEWORLD_IMULTIPLAYERSERVERLISTENER_H
#define CUBEWORLD_IMULTIPLAYERSERVERLISTENER_H


class IMultiplayerServerListener {

};


#endif //CUBEWORLD_IMULTIPLAYERSERVERLISTENER_H
