//
// Created by Peter Chen on 5/29/16.
//

#ifndef CUBEWORLD_AVATARCOMPONENTPHYSICS_H
#define CUBEWORLD_AVATARCOMPONENTPHYSICS_H


class AvatarComponentPhysics {

};


#endif //CUBEWORLD_AVATARCOMPONENTPHYSICS_H
