//
// Created by Peter Chen on 5/29/16.
//

#ifndef CUBEWORLD_ITEMCOMPONENTAUTODESTORY_H
#define CUBEWORLD_ITEMCOMPONENTAUTODESTORY_H


class ItemComponentAutoDestory {

};


#endif //CUBEWORLD_ITEMCOMPONENTAUTODESTORY_H
